### PR TITLE
Propose adding type

### PR DESCRIPTION
**Pull request by denis-yuen**
Add type and other changes before v1

### CODE REVIEW

**Comment by denis-yuen** [comment]
@jacarey any thoughts? we should probably close this before end of day unless you have any thoughts/new ideas for changes

**Comment by jacarey** [comment]
I think this is a good idea. What did you have in mind for initial types. Workflow and Task.

I think we should be careful with the nouns that we pick and make sure it is clear what each on represents.

**Comment by denis-yuen** [comment]
I haven't decided whether we should bake-in initial types or just leave it open-ended with users agreeing to use common types, but the schema not enforcing it. Right now, I left it open-ended. 

Initially, my thoughts would be workflow, task/tool as well.

**Comment by jacarey** [comment]
That sounds good to me :+1:

**Pull request merged**
