### PR TITLE
Remove CWL/WDL paragraph

### PR DESCRIPTION
**Pull request by mr-c**
as per https://github.com/ga4gh/workflow-execution-schemas/issues/7

### CODE REVIEW

**Comment by mr-c** [comment]
Thank you @vdauwera I've adopted and adapted your suggestion. Once approved here I'll move it to the other two PRs as well.

**Comment by mr-c** [comment]
Whoa, I put it in the wrong place, one moment

**Comment by mr-c** [comment]
Ready for review & merging

**Comment by geoffjentry** [comment]
See comment I made here: https://github.com/ga4gh/workflow-execution-schemas/issues/7

**Comment by denis-yuen** [comment]
@mr-c  @vdauwera  
Seeing something odd. I see the commit 84151c7 
But maybe it was made to a different branch because the content doesn't show up in "Files changed"

**Comment by mr-c** [comment]
@denis-yuen Yes, I adapted the suggested changes from @vdauwera into my commit https://github.com/ga4gh/tool-registry-schemas/commit/84151c7edef8b3a1224ce6f70c0d67eac6c4a5e1 and the `git reset -force HEAD^^; git push -f` removed them due to @geoffjentry 's comment: https://github.com/ga4gh/workflow-execution-schemas/issues/7#issuecomment-282723157

**Comment by denis-yuen** [comment]
Ah, rats. That one didn't seem controversial.

**Comment by geoffjentry** [comment]
@denis-yuen Yeah, I would rather see what you suggested a while back (not part of these PRs as @mr-c has pointed out) where we list the technologies we're interested in as a group - of which WDL & CWL are a small part. I think that by highlighting one or both of those it sends a very incorrect message -> Example, the guy who joined the call today who was from "the other CWL group". As @mr-c is always quick to point out, containers & workflows is not a CWL group

**Comment by mr-c** [comment]
@geoffjentry heh, I only caught the end of his comment -- makes more sense now :-)

**Comment by geoffjentry** [comment]
@mr-c They both have CW in the name :) 

I'll merge these once i get a chance, hopefully soon. I'll also try to put together a start for a formal proposal of an official description based on what @denis-yuen said previously.

**Pull request merged**
